// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGkGH2WHCN7i3XYmRCRDAtra_AeJI-45w',
    appId: '1:688336632854:web:14521ac6bcc30d7b1fc937',
    messagingSenderId: '688336632854',
    projectId: 'chat-flutter-uni',
    authDomain: 'chat-flutter-uni.firebaseapp.com',
    storageBucket: 'chat-flutter-uni.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqPV2QiaK5-Z6ptnKeeFcHM0CR75LUDb8',
    appId: '1:688336632854:android:66628e3c47c350a71fc937',
    messagingSenderId: '688336632854',
    projectId: 'chat-flutter-uni',
    storageBucket: 'chat-flutter-uni.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOJFkRcuaQT-yebWk91jgAdIEiPtMjLag',
    appId: '1:688336632854:ios:25b7f9571aa755951fc937',
    messagingSenderId: '688336632854',
    projectId: 'chat-flutter-uni',
    storageBucket: 'chat-flutter-uni.appspot.com',
    androidClientId: '688336632854-opmee3as07skmlnd2qrolae68656gr67.apps.googleusercontent.com',
    iosClientId: '688336632854-94s4biff8q5g043gh6gig0t9m6bnnkrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOJFkRcuaQT-yebWk91jgAdIEiPtMjLag',
    appId: '1:688336632854:ios:25b7f9571aa755951fc937',
    messagingSenderId: '688336632854',
    projectId: 'chat-flutter-uni',
    storageBucket: 'chat-flutter-uni.appspot.com',
    androidClientId: '688336632854-opmee3as07skmlnd2qrolae68656gr67.apps.googleusercontent.com',
    iosClientId: '688336632854-94s4biff8q5g043gh6gig0t9m6bnnkrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatt',
  );
}
